# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:p6spy:postgresql://postgres:5432/jiujitsu   # ✅ 변경
    username: jiujitsu
    password: jiujitsu_pw
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver   # ✅ 변경
    initialization-mode: never
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# logging
logging:
  level:
    p6spy: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off

# CORS
cors:
  allowed-origins:
    - https://dev-api.bjj-oss.kr
    - http://localhost:3000
    #todo: 로컬호스트 삭제

# Swagger server URL
springdoc:
  swagger-ui:
    server:
      url: https://dev-api.bjj-oss.kr
