# application.yml
spring:
  mvc:
    servlet:
      path: /api
  application:
    name: api
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} %-5level [%X{traceId:-}] %logger{36} - %msg%n"

# 공통 Actuator 설정
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "never"
      probes:
        enabled: true

# JWT 공통
jwt:
  secret: jiujitsu-secret-key-for-development-only-change-in-production-environment
  access-token-validity: 3600000
  refresh-token-validity: 604800000
  temporary-token-validity: 300000

# Swagger/OpenAPI 공통
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none

# Apple Key 공통
apple:
  filePath: ./jiujitsuLab_AuthKey_Z3HRNZG68M.p8

# fcm 공통
fcm:
  file_path: resources/fcm/jiu-jitsu-lab-firebase-adminsdk-fbsvc-3955e0b618.json
  url: https://fcm.googleapis.com/v1/projects/jiu-jitsu-lab/messages:send
  google_api: https://www.googleapis.com/auth/cloud-platform
  project_id: jiu-jitsu-lab

# imageKit
imagekit:
  private-key: ${IMAGEKIT_PRIVATE_KEY}
  api-url: https://api.imagekit.io/v1/files/