# ?? ??
logMessageFormat=com.jiujitsu.api.global.config.P6spySqlFormatter
customLogMessageFormat=%(currentTime)|%(executionTime)ms|%(category)|connection %(connectionId)\n%(sql)

# ?? ?? ??
appender=com.p6spy.engine.spy.appender.Slf4JLogger

# ?? ?? ??
executionThreshold=0

# ?? ????
excludecategories=info,debug,result,commit,resultset