services:
  nginx:
    image: nginx:1.29
    container_name: rp-nginx
    ports: ["127.0.0.1:8080:80"]   # Cloudflare Tunnel이 여기에 붙음
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on: [api]
    networks: [edge]

  api:
    image: ghcr.io/jiu-jitsu-org/jiu-jitsu-backend-api:latest-develop
    container_name: app-api
    restart: unless-stopped
    # ✅ 호스트 포트 매핑 제거 (중요)
    # ports:
    #   - "8080:8080"
    expose:
      - "8080"                     # 같은 네트워크 컨테이너들에만 8080 노출
    environment:
      SPRING_PROFILES_ACTIVE: dev
      IMAGEKIT_PRIVATE_KEY: private_wxr5zzataMwfAQvBitzvLTVWS94=
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP || exit 1"]
      interval: 30s
      timeout: 3s
      start_period: 30s
    pull_policy: always
    networks: [edge]

  webhook:
    build:
      context: ./webhook
      dockerfile: Dockerfile
    image: webhook-with-docker:latest   # 선택(캐싱/표시용)
    container_name: deploy-webhook
    command: [ "-hooks=/hooks/hooks.json","-template","-port=9000","-verbose" ]
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - GHCR_USERNAME=${GHCR_USERNAME}
      - GHCR_PAT=${GHCR_PAT}
    volumes:
      - ./webhook:/hooks:ro
      - ..:/stack
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [ edge ]
    restart: unless-stopped



networks:
  edge: {}
